// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJ9MtD8ENYP2fJKirCMt_Hvipud-1LYg',
    appId: '1:178124523408:web:c3c4d8d5b3f8f406249515',
    messagingSenderId: '178124523408',
    projectId: 'fir-appdio',
    authDomain: 'fir-appdio.firebaseapp.com',
    databaseURL: 'https://fir-appdio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-appdio.appspot.com',
    measurementId: 'G-H1HQPFPYJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7WzBeUKcXDOIzSnMpZzWfxj2yCWMfuY',
    appId: '1:178124523408:android:90717d29bc2d4271249515',
    messagingSenderId: '178124523408',
    projectId: 'fir-appdio',
    databaseURL: 'https://fir-appdio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-appdio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1DrUZt0a6gfWQDvkMIsxrKUunM0D1doU',
    appId: '1:178124523408:ios:ffb88e9b05777e7d249515',
    messagingSenderId: '178124523408',
    projectId: 'fir-appdio',
    databaseURL: 'https://fir-appdio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-appdio.appspot.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1DrUZt0a6gfWQDvkMIsxrKUunM0D1doU',
    appId: '1:178124523408:ios:c17473e2b666f17f249515',
    messagingSenderId: '178124523408',
    projectId: 'fir-appdio',
    databaseURL: 'https://fir-appdio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-appdio.appspot.com',
    iosBundleId: 'com.example.firebaseapp.RunnerTests',
  );
}
